### ISSUE TITLE
Project: Calculator the Game solution visualiser

### ISSUE THREAD

**Issue by CalvinLe360** [CalvinLe360/calvinle360.github.io#3]
I made that a while ago lol

## Tasks
- [ ] Obtain a copy
- [ ] UI Improvement pass
- [ ] Custom puzzle / sandbox mode
## Improvements
- [ ] A simulated calculator side by side to the visualiser to show the game state
